#####################################################
##-------------------------------------------------##
##   FICHERO DE PROPIEDADES DEL ALGORITMO A USAR   ##
##-------------------------------------------------##
#####################################################

## Propiedad que cambia el algoritmo de ejecucion
## Actualmente estan implementados:
##   - SA (Simulated Annealing)
##   - VNS (Variable Neighborhood Search)
##   - alg1 (Opcion 1)
##   - alg2 (Opcion 2)
Algoritmo=SA

## Tiempo de ejecucion del que dispone el algoritmo (en minutos)
Tiempo_De_Ejecucion_Disponible=15

## Funciones Objetivo - Posibles valores:
# - fun1
# - fun2
# - fun3
# - reduccionATC_Restr_Sim_Contin
#       -> Reducir controladores
#       -> Reducir incumplimiento de restricciones
#       -> Aumentar similitud a los estadillos
#       -> Procurar continuidad al momento del cambio
Funcion_Objetivo=reduccionControladoresYRestriccionesYSimilitudYContinuidad

## Pesos asignados a los distintos subobjetivos de la funcion objetivo (suma 1)
## 	- Fitness1:  Reducir controladores
## 	- Fitness2:  Reducir incumplimiento de restricciones
## 	- Fitness3:  Aumentar similitud a los estadillos
## 	- Fitness4:  Procurar continuidad al momento del cambio
Peso_1=0.52
Peso_2=0.27
Peso_3=0.15
Peso_4=0.06

##Tamanio del slot (Intervalo de tiempo en minutos)
Discretizacion_Del_Tiempo=5