########################################################
##----------------------------------------------------##
## FICHERO DE PROPIEDADES DE LAS RESTRICCIONES A USAR ##
##----------------------------------------------------##
########################################################

##Porcentajes de descanso para los turnos de dia y noche (0.25 --> 25%)
Porcentaje_De_Descanso_En_Turno_Diurno=0.25
Porcentaje_De_Descanso_En_Turno_Nocturno=0.33

##Tiempos de trabajo requeridos (maximo, minimo, y minimo en la misma posicion)
Tiempo_De_Trabajo_Maximo_Consecutivo=120
Tiempo_De_Trabajo_Minimo_Consecutivo=15
Tiempo_De_Trabajo_Minimo_En_Posicion=15

##Tiempos de descanso requeridos (consecutivo y en ventana de 2:30h)
Tiempo_De_Descanso_Minimo_Consecutivo=15
Tiempo_De_Descanso_Minimo_No_Continuo=30

##Numero de sectores no afines maximo por el que puede pasar un controlador
Numero_Maximo_De_Sectores_Controlados=3

##Porcentajes de trabajo maximos y minimos en posicion (ejecutivo/planificador)
Porcentaje_De_Trabajo_Maximo_En_Posicion=0.6
Porcentaje_De_Trabajo_Minimo_En_Posicion=0.4
