#######################################################
##---------------------------------------------------##
##      FICHERO DE PROPIEDADES DEL ALGORITMO SA      ##
##---------------------------------------------------##
#######################################################

##Metodos de calculo de alguno de los parametros de ejecucion
Metodo_De_Temperatura_Inicial=Fija
Metodo_De_Calculo_Del_Descenso=Krikpatric
Metodo_De_Calculo_De_Iteraciones=CutOff

##Temperatura inicial del algoritmo
Temperatura_Inicial=0.005
##Descenso de la temperatura 
Descenso_De_La_Temperatura=0.975
##Iteraciones necesarias para el descenso de la temperatura
Iteraciones_Para_Descenso_De_La_Temperatura=3000

##Condiciones de parada (se debe mejorar un x% del valor objetivo durante y iteraciones)
Porcentaje_De_Mejora=0.035
Iteraciones_De_Comprobacion=50000
Porcentaje_De_Soluciones_Mejoradas=0.02


##Posibles valores: movimiento1,2,3,4,5... (Mas usados: 6, 12, 15, 17)
## - En la clase DeciderMove esta explicado el funcionamiento de los movimientos y sus diferencias
Movimiento=movimiento15


##Tamanio maximo y minimo de los movimientos que generan soluciones del entorno (en minutos) 
Periodo_Maximo_De_Movimiento=60
Periodo_Minimo_De_Movimiento=10

##Permite crear un grid adaptativo durante la ejecucion del algoritmo para el mov17/25
move17_adapt_max=false

##Mínimo y máximo de intervalos consecutivos que se pueden seleccionar para realizar el movimiento 15 y derivados
Numero_Minimo_De_Intervalos_Utilizados=1
Numero_Maximo_De_Intervalos_Utilizados=3

##Número de iteraciones tras las que se refina la grid (movimiento 14 y derivados)
Ciclo_De_Refinamiento_De_La_Rejilla=1500

