#######################################################
##---------------------------------------------------##
##      FICHERO DE PROPIEDADES DEL ALGORITMO VNS     ##
##---------------------------------------------------##
#######################################################

## Numero de iteraciones permitidas en la busqueda (estocastica) local
Numero_Maximo_Iteracciones_Sin_Mejora_Local=70

## Porcentaje sin mejora que debe haber como maximo (condicion de parada [junto con el tiempo])
Porcentaje_De_Mejora=0.035

## Se comprueba la condicion de parada de porcentaje de mejora cada este numero de iteraciones
Iteraciones_De_Comprobacion=50000

# Indica el tipo de VNS que se esta utilizando.
# Actualmente estan implementados:
#   - VND (Descendent VNS)
#   - RVNS (Reduced VNS)
#   - BVNS (Basic VNS)
#   - GVNS (General VNS)
#   - SVNS (Skewed VNS)
Variante_De_VNS=VND


# Aqui se define que estructuras de vecindad se van a utilizar en el
# algoritmo. Para saber cuales son cada uno ver documentacion.
#
# USO: escribir los posibles valores separados por comas y SIN ESPACIOS.
# La estructura de vecindad se definira segun el orden indicado aqui,
# y utilizara un k_max igual al numero de movimientos aqui indicados.
#
# POSIBLES VALORES:
#   - movMaxCarga
#   - movMaxCarga.1,movMaxCarga.2,movMaxCarga.3,movMaxCarga.4,movMaxCarga.5,movMaxCarga.6
#   - movRejilla
#   - movRejilla.1,movRejilla.2,movRejilla.3,movRejilla.4,movRejilla.5,movRejilla.6
#   - movLibre
Lista_De_Vecindarios=movRejilla,movMaxCarga.1,movMaxCarga.2,movMaxCarga.3,movMaxCarga.4,movMaxCarga.5,movMaxCarga.6,movLibre
#Lista_De_Vecindarios=movMaxCarga,movRejilla.1,movRejilla.2,movRejilla.3,movRejilla.4,movRejilla.5,movRejilla.6,movLibre
#Lista_De_Vecindarios=movMaxCarga.1,movMaxCarga.2,movMaxCarga.3,movMaxCarga.4,movMaxCarga.5,movMaxCarga.6,movRejilla.1,movRejilla.2,movRejilla.3,movRejilla.4,movRejilla.5,movRejilla.6,movLibre
#Lista_De_Vecindarios=movRejilla.1,movRejilla.2,movRejilla.3,movRejilla.4,movRejilla.5,movRejilla.6,movMaxCarga.1,movMaxCarga.2,movMaxCarga.3,movMaxCarga.4,movMaxCarga.5,movMaxCarga.6,movLibre

Alfa_Para_SVNS=18.5

# funcion de distancia a utilizar:
#   - "fitness": |f(x) - f(x')|
#   - "slots": num slots distintos entre si
Funcion_De_Distancia_Para_SVNS=slots